{% set version = "0.2.14" %}

package:
  name: ruamel.yaml.clib
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/r/ruamel.yaml.clib/ruamel.yaml.clib-{{ version }}.tar.gz
    sha256: 803f5044b13602d58ea378576dd75aa759f52116a0232608e8fdada4da33752e

build:
  number: 0
  script:
    - cythonize _ruamel_yaml.pyx
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - pip
    - setuptools
  run:
    - python

test:
  # Use downstreams and importlib.util.find_spec instead of a usual import test
  # since we have a yet-to-be-resolved cyclic dependency with ruamel.yaml because
  # ruamel.yaml.clib needs the "ruamel.yaml" Python namespace package which is
  # currently shipped with all other ruamel.yaml code in our ruamel.yaml package.
  # See https://github.com/conda-forge/ruamel.yaml-feedstock/issues/119 for details.
  downstreams:
    - ruamel.yaml
  commands:
    - python -c "from importlib.util import find_spec; assert find_spec('_ruamel_yaml')"

about:
  home: https://sourceforge.net/projects/ruamel-yaml-clib/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C version of reader, parser and emitter for ruamel.yaml derived from libyaml

extra:
  recipe-maintainers:
    - mbargull
    - ocefpaf
