{% set version = "0.2.2" %}

package:
  name: ruamel.yaml.clib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/ruamel.yaml.clib/ruamel.yaml.clib-{{ version }}.tar.gz
  sha256: 2d24bd98af676f4990c4d715bcdc2a60b19c56a3fb3a763164d2d8ca0e806ba7

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

# test:
#   requires:
#     - ruamel.yaml
#   imports:
#     - _ruamel_yaml

about:
  home: https://bitbucket.org/ruamel/yaml.clib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C version of reader, parser and emitter for ruamel.yaml derived from libyaml

extra:
  recipe-maintainers:
    - ocefpaf
