{% set version = "0.2.6" %}

package:
  name: ruamel.yaml.clib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/ruamel.yaml.clib/ruamel.yaml.clib-{{ version }}.tar.gz
  sha256: 4ff604ce439abb20794f05613c374759ce10e3595d1867764dd1ae675b85acbd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    # Try to work around some recent issues with setuptools
    - setuptools <58.5
  run:
    - python

# test:
#   requires:
#     - ruamel.yaml
#   imports:
#     - _ruamel_yaml
test:
  commands:
    - echo "OK"

about:
  home: https://bitbucket.org/ruamel/yaml.clib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C version of reader, parser and emitter for ruamel.yaml derived from libyaml

extra:
  recipe-maintainers:
    - ocefpaf
